export const GET_ONE_SALESPERSON = 'GET_ONE_SALESPERSON';
export const GET_ONE_SALESPERSON_SUCCESS = 'GET_ONE_SALESPERSON_SUCCESS';

export const GET_ALL_SALESPERSONS = 'GET_ALL_SALESPERSONS';
export const GET_ALL_SALESPERSONS_SUCCESS = 'GET_ALL_SALESPERSONS_SUCCESS';
export const GET_ALL_SALESPERSONS_ERROR = 'GET_ALL_SALESPERSONS_ERROR';

export const ADD_SALESPERSON = 'ADD_SALESPERSON';

export const EDIT_SALESPERSON = 'EDIT_SALESPERSON';

export const GET_WAREHOUSE_SHOPS = 'GET_WAREHOUSE_SHOPS';
export const GET_WAREHOUSE_SHOPS_SUCCESS = 'GET_WAREHOUSE_SHOPS_SUCCESS';

export const GET_SALESPERSON_SHOPS = 'GET_SALESPERSON_SHOPS';
export const GET_SALESPERSON_SHOPS_SUCCESS = 'GET_SALESPERSON_SHOPS_SUCCESS';

export const ADD_SHOPS_TO_SALESPERSON = 'ADD_SHOPS_TO_SALESPERSON';

export const GET_SALESPERSON_DAILY_PRODUCTS = 'GET_SALESPERSON_DAILY_PRODUCTS';
export const GET_SALESPERSON_DAILY_PRODUCTS_SUCCESS =
  'GET_SALESPERSON_DAILY_PRODUCTS_SUCCESS';

export const ADD_NEW_DAILY_PRODUCT = 'ADD_NEW_DAILY_PRODUCT';

// export const CHANGE_DAILY_PRODUCT_COUNT = 'CHANGE_DAILY_PRODUCT_COUNT';
