export const SET_SALESPERSONS_FILTER = 'SALESPERSONS_FILTER';

export const GET_ONE_SALESPERSON = 'GET_ONE_SALESPERSON';
export const GET_ONE_SALESPERSON_SUCCESS = 'GET_ONE_SALESPERSON_SUCCESS';

export const GET_ALL_SALESPERSONS = 'GET_ALL_SALESPERSONS';
export const GET_ALL_SALESPERSONS_SUCCESS = 'GET_ALL_SALESPERSONS_SUCCESS';
export const GET_ALL_SALESPERSONS_ERROR = 'GET_ALL_SALESPERSONS_ERROR';

export const ADD_SALESPERSON = 'ADD_SALESPERSON';
