export const GET_WAREHOUSE_SALES = 'GET_WAREHOUSE_SALES';
export const GET_WAREHOUSE_SALES_SUCCESS = 'GET_WAREHOUSE_SALES_SUCCESS';
export const GET_WAREHOUSE_SALES_ERROR = 'GET_WAREHOUSE_SALES_ERROR';
export const M_GET_MANAGER_WAREHOUSE = 'M_GET_MANAGER_WAREHOUSE';
export const M_GET_MANAGER_WAREHOUSE_SUCCESS =
  'M_GET_MANAGER_WAREHOUSE_SUCCESS';
