export const GET_WAREHOUSE_SALES = 'GET_WAREHOUSE_SALES';
export const GET_WAREHOUSE_SALES_SUCCESS = 'GET_WAREHOUSE_SALES_SUCCESS';
export const GET_WAREHOUSE_SALES_ERROR = 'GET_WAREHOUSE_SALES_ERROR';
