export const GET_ALL_WAREHOUSE_PRODUCTS = 'GET_ALL_WAREHOUSE_PRODUCTS';
export const GET_ALL_WAREHOUSE_PRODUCTS_SUCCESS =
  'GET_ALL_WAREHOUSE_PRODUCTS_SUCCESS';
export const GET_ALL_WAREHOUSE_PRODUCTS_ERROR =
  'GET_ALL_WAREHOUSE_PRODUCTS_ERROR';

export const ADD_PRODUCT_TO_WAREHOUSE = 'ADD_PRODUCT_TO_WAREHOUSE';

export const CHANGE_WAREHOUSE_PRODUCT_QUANTITY =
  'CHANGE_WAREHOUSE_PRODUCT_QUANTITY';

export const DELETE_WAREHOUSE_PRODUCT = 'DELETE_WAREHOUSE_PRODUCT';
export const DELETE_WAREHOUSE_PRODUCT_SUCCESS =
  'DELETE_WAREHOUSE_PRODUCT_SUCCESS';
