export const GET_LEAVES = 'GET_LEAVES';
export const GET_LEAVES_SUCCESS = 'GET_LEAVES_SUCCESS';
export const GET_LEAVES_ERROR = 'GET_LEAVES_ERROR';

export const UPDATE_LEAVE = 'UPDATE_LEAVE';
export const UPDATE_LEAVE_SUCCESS = 'UPDATE_LEAVE_SUCCESS';
export const UPDATE_LEAVE_ERROR = 'UPDATE_LEAVE_ERROR';
