export const GET_ONE_MANAGER = 'GET_ONE_MANAGER';
export const GET_ONE_MANAGER_SUCCESS = 'GET_ONE_MANAGER_SUCCESS';
export const GET_ALL_MANAGERS = 'GET_ALL_MANAGERS';
export const GET_ALL_MANAGERS_SUCCESS = 'GET_ALL_MANAGERS_SUCCESS';
