export const GET_ALL_SALESPERSONS = 'ADMIN/GET_ALL_SALESPERSONS';
export const GET_ALL_SALESPERSONS_SUCCESS =
  'ADMIN/GET_ALL_SALESPERSONS_SUCCESS';
export const GET_ONE_SALESPERSON_DETAILS = 'ADMIN/GET_ONE_SALESPERSON_DETAILS';
export const GET_ONE_SALESPERSON_DETAILS_SUCCESS =
  'ADMIN/GET_ONE_SALESPERSON_DETAILS_SUCCESS';
export const GET_ONE_SALESPERSON_ANALYTICS_SALES =
  'ADMIN/GET_ONE_SALESPERSON_ANALYTICS_SALES';
export const GET_ONE_SALESPERSON_ANALYTICS__SALES_SUCCESS =
  'ADMIN/GET_ONE_SALESPERSON_ANALYTICS_SALES_SUCCESS';
export const GET_ONE_SALESPERSON_PRODUCTS_ONE_DAY =
  'ADMIN/GET_ONE_SALESPERSON_PRODUCTS_ONE_DAY';
export const GET_ONE_SALESPERSON_PRODUCTS_ONE_DAY_SUCCESS =
  'ADMIN/GET_ONE_SALESPERSON_PRODUCTS_ONE_DAY_SUCCESS';
export const GET_SALESPERSON_LEADERBOARD = 'ADMIN/GET_SALESPERSON_LEADERBOARD';
export const GET_SALESPERSON_LEADERBOARD_SUCCESS =
  'ADMIN/GET_SALESPERSON_LEADERBOARD_SUCCESS';
