export const GET_WAREHOUSES = 'ADMIN/GET_WAREHOUSES';
export const GET_WAREHOUSE_SUCCESS = 'ADMIN/GET_WAREHOUSES_SUCCESS';
export const GET_ONE_WAREHOUSE = 'ADMIN/GET_ONE_WAREHOUSE';
export const GET_ONE_WAREHOUSE_SUCCESS = 'ADMIN/GET_ONE_WAREHOUSE_SUCCESS';
export const ADD_WAREHOUSE = 'ADMIN/ADD_WAREHOUSE';
export const ASSIGN_MANAGER = 'ADMIN/ASSIGN_MANAGER';
export const GET_ONE_WAREHOUSE_ANALYTICS = 'ADMIN/GET_ONE_WAREHOUSE_ANALYTICS';
export const GET_ONE_WAREHOUSE_ANALYTICS_SUCCESS =
  'ADMIN/GET_ONE_WAREHOUSE_ANALYTICS_SUCCESS';
