export const GET_WAREHOUSES = 'GET_WAREHOUSES';
export const GET_WAREHOUSE_SUCCESS = 'GET_WAREHOUSES_SUCCESS';
export const GET_ONE_WAREHOUSE = 'GET_ONE_WAREHOUSE';
export const GET_ONE_WAREHOUSE_SUCCESS = 'GET_ONE_WAREHOUSE_SUCCESS';
