export const GET_SALESPERSONS_SALES_BY_DATE_RANGE =
  'GET_SALESPERSON_SALES_BY_DATE_RANGE';

export const GET_SALESPERSONS_SALES_BY_DATE_RANGE_SUCCESS =
  'GET_SALESPERSONS_SALES_BY_DATE_RANGE_SUCCESS';

export const GET_SALESPERSONS_SALES_BY_DATE_RANGE_ERROR =
  'GET_SALESPERSONS_SALES_BY_DATE_RANGE_ERROR';
